### ISSUE TITLE
Problemas na parte de gerenciamento de usuários do projeto final

### ISSUE THREAD

**Issue by netoabel** [Webschool-io/be-mean-instagram-mongodb-projects#45]
No projeto final, na parte de gerenciamento de usuários, há os seguintes itens: 

```
Crie um usuário com permissões APENAS de Leitura.
Crie um usuário com permissões de Escrita e Leitura.
Adicionar o papel grantRolesToUser e revokeRole para o usuário com Escrita e Leitura.
Remover o papel grantRolesToUser para o usuário com Escrita e Leitura.
Listar todos os usuários com seus papéis e ações.
```

Identifiquei dois problemas nesse tópico:
1. Não existem os papéis `grantRolesToUser` e `revokeRole`. Na verdade esses itens são **ações** garantidas pelo papel `userAdmin`;
2. Não é possível listar todas as **ações** de todos os usuários. Você consegue apenas listar os usuários e seus respectivos **papéis**. As ações são fixas para cada papel e só podem ser listadas fazendo uma consulta individual a cada papel com o método `db.getRole` com a opção `showPrivileges`.

Eu posso estar errado, mas talvez seja melhor reformular essa parte :P

**Comment by suissa** [comment]
Na verdade é só vc dar as autorização de userAdmin para eu suer criado.
